const { pool } = require('../utils/database');


exports.getIndex = (req, res, next) => {
    res.status(200).json({ message: 'Hello Admin' });
}

exports.getHealthcheck = (req, res, next) => {
    // Code generated by Chatgpd
    const query = 'SELECT NOW()'; // Replace with your actual database connectivity check logic

    pool.getConnection((err, connection) => {
        if (err) {
            console.error(err);
            return res.status(500).json({ status: 'failed', message: ['connection string'] });
        }

        connection.query(query, (err, result) => {
            connection.release();

            if (err) {
                console.error(err);
                return res.status(500).json({ status: 'failed', message: ['connection string'] });
            }

            res.status(200).json({ status: 'OK', message: ['connection string'] });
        });
    });
}