import { Inter, Cabin } from 'next/font/google'
import './globals.css'
import Navbar from '@/Components/Navbar'
import { AuthProvider } from '@/Components/Context'

const inter = Inter({ subsets: ['latin'] })

const cabin = Cabin({
  weight: ['400','700'],
  subsets: ['latin']
})

export const metadata = {
  title: 'Ntuaflix',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cabin.className}>
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
